# Generated by Django 2.2.6 on 2021-07-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author_constraint',
        ),
    ]
